- name: Deploy preview site
  uses: cssjpn/blog-gh-actions/deploy-preview@v1
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    azure-storage-connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
    preview-base-url: "https://jpazureidblogstorage.z5.web.core.windows.net/"